### ISSUE TITLE
What about crop image?

### ISSUE THREAD

**Issue by hidabe** [coomar2841/image-chooser-library#10]
I am thinking about add crop image with https://github.com/lvillani/android-cropimage

Where could i add it?

**Comment by jagatappv** [comment]
+1
i am also waiting for this.. :dancer:

**Comment by coomar2841** [comment]
Ok, Will be adding it in the next release. Probably in a week.

**Comment by coomar2841** [comment]
On second thoughts, can't the application directly use that library? It's pretty easy to integrate it with your apps. I don't see a reason why I should either re-write or re-package this library with this ICL library.

**Comment by jagatappv** [comment]
It would be good for user to use single library instead of handling two separate one.

**Comment by timmolter** [comment]
@coomar2841 That's actually what IU ended up doing.

**Comment by coomar2841** [comment]
I understand that. But then, I would also be tempted to integrate other image handling libraries. The other libraries already do an amazing job and when they would update their libraries to add new features or bug fixes, I would also have to release ICL again, although I haven't made any changes to ICL code. People, eventually, who would have bugs in the older version, would probably end up using the updated library separately.

**Comment by coomar2841** [comment]
@timmolter Nice :+1:

**Comment by Jaymassena** [comment]
My 2 cents. Image chooser should be great at picking media and that's it. Packing in more is a slippery slope that never ends.

**Comment by coomar2841** [comment]
Closing this now.
