### ISSUE TITLE
Manage cache

### ISSUE THREAD

**Issue by Shusshu** [coomar2841/image-chooser-library#102]
`manageDiretoryCache(...)`  is called but never does anything because `clearOldFiles` is always `false`

How did you plan to configure this behaviour?

**Comment by coomar2841** [comment]
You are right. Clearing old files is not yet fully implemented, since I am on a refactoring mission on this. Expected to have this done with the next release.

**Comment by Shusshu** [comment]
Good to hear.
any ideas even rough when you plan to release the next one?

**Comment by coomar2841** [comment]
Probably in 2 weeks time. May be 3. I am a little caught up with other
stuff.


*Thanks and Regards,Kumar Bibek*


*http://techdroid.kbeanie.com
<http://techdroid.kbeanie.com>http://www.kbeanie.com
<http://www.kbeanie.com>*

On Tue, Aug 18, 2015 at 3:46 PM, Benoit Billington <notifications@github.com

**Comment by coomar2841** [comment]
Added public method, clearOldFiles. Call this right after creating the manager objects.
