### ISSUE TITLE
It works to slowly

### ISSUE THREAD

**Issue by comk** [coomar2841/image-chooser-library#105]
hello ,It is really amazing for the lib's function .
but it works so slowly when chooser image.

**Comment by coomar2841** [comment]
Yes, it's a bit slower than normal, but in most cases it's quite fast. I will keep this issue open and see how I can optimize this.

**Comment by comk** [comment]
thanks for reply,hope this could be better

**Comment by comk** [comment]
Thanks for your development for this library
