### ISSUE TITLE
/MediaProcessorThread.java line 204

### ISSUE THREAD

**Issue by acedward** [coomar2841/image-chooser-library#117]
Hi,

It looks like the line
```java
bitmap = BitmapFactory.decodeFile(fileImage);
```
is missing the second argument:
```java
bitmap = BitmapFactory.decodeFile(fileImage, options);
```

(I was getting some out of memory issues)

https://github.com/coomar2841/image-chooser-library/blob/dev/image-chooser-library/src/main/java/com/kbeanie/imagechooser/threads/MediaProcessorThread.java#L204

**Comment by coomar2841** [comment]
Yeah, you are right. Will fix this right away.

**Comment by coomar2841** [comment]
Done.
