### ISSUE TITLE
decoder->decode returned false

### ISSUE THREAD

**Issue by matskr90dev** [coomar2841/image-chooser-library#120]
Phone: Nexus 4
Android: 5.1.1

I use code similar to your example app:

    @Override
    public void onImageChosen(final ChosenImage image) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Picasso.with(MainActivity.this).load(image.getFileThumbnail()).fit().into(imageViewThumbnail);
            }
        });
    }

But I got:
D/skia: --- decoder->decode returned false

What's wrong?

**Comment by coomar2841** [comment]
That happens, when for some images, Android is not able to generate a bitmap for an image. Try searching for this error on SO, and you will find some information. But, I will keep this issue open and see what I can do to solve this.

**Comment by parkjaeiek** [comment]
i have same issue too.
