### ISSUE TITLE
Since 1.5.0 thumbnails are not generated properly

### ISSUE THREAD

**Issue by StigZord** [coomar2841/image-chooser-library#127]
Since 1.5.0 thumbnails are not generated properly for me (in v1.4.4 it works fine).
Using file explorer I can see that in theory thumbnails `name_fact_1.jpg` and `name_fact_2.jpg` are generated but both size is 0 Bytes, and can't be opened. Original picture is generated as it should tho.

Also this code:

```java
    @Override
    public void onImageChosen(ChosenImage chosenImage) {
        photoFilePath = chosenImage.getFilePathOriginal();
        photoThumbnailPath = chosenImage.getFileThumbnailSmall();

        Log.d(TAG, "filePath: "+photoFilePath);
        Log.d(TAG, "photoThumbnailPath: "+photoThumbnailPath);
    }
```

will log this:
````
TAG: filePath: /storage/emulated/0/folder/1446494059426.jpg
TAG: photoThumbnailPath: /storage/emulated/0/folder/1446494059426.jpg
````

On the other hand in version 1.4.4 as I mentioned it works fine, thumbnails are generated and path is returned to the thumbnail as it should.

If something is not clear in my explanation or u need any more details let me know.
Cheers!

**Comment by coomar2841** [comment]
Thanks. I am aware of it. Looking into this issue.

**Comment by coomar2841** [comment]
Can you try 1.5.1 once? This actually happens for only some files. Not sure, but still digging into this.

**Comment by StigZord** [comment]
Actually I already tried it on both 1.5.1 and 1.5.0... it works on 1.4.4 tho.
Not sure if it will be of any help, but I'm picking pretty big .jpg photos over 3.5MB, and it didn't work for any of this photos.

**Comment by coomar2841** [comment]
The latest release should fix this issue.
