### ISSUE TITLE
Bug from video recording, Android 4.1 Galaxy S3 Mini

### ISSUE THREAD

**Issue by hidabe** [coomar2841/image-chooser-library#14]
Hello again,

I have detected another bug trying use image-chooser-library from one GalaxyS3 Mini with Android 4.1, it dont show ok and cancel buttons.

Have you detected any same it?

Regards and very thanks for your work.

**Comment by Noam-Modai** [comment]
Still same issue S3 Mini 4.1.2.
seems that device needs the same solution as Gingerbread devices.
