### ISSUE TITLE
Not working with Android 6.0

### ISSUE THREAD

**Issue by ravimittal99** [coomar2841/image-chooser-library#141]
It works great upto Lollipop. 

I requested permissions both for camera and external storage. Both are granted. And when trying to pick photo from camera, imageChooserManager.choose() throws an exception:

com.kbeanie.imagechooser.exceptions.ChooserException: Error creating directory: /sdcard/bichooser

**Comment by coomar2841** [comment]
Do you have WRITE_STORAGE permission in the manifest?

**Comment by umair088** [comment]
Getting same issue in 6.0 else are fine.

**Comment by fastwow** [comment]
Have the same issue too
