### ISSUE TITLE
EISDIR error on selecting image

### ISSUE THREAD

**Issue by adreamer** [coomar2841/image-chooser-library#150]
![screenshot_2016-01-16-20-11-07-4](https://cloud.githubusercontent.com/assets/1107765/12779682/af51da84-caac-11e5-81e4-c3291403ee47.png)

On Samsung Galaxy Grand 2 (Android 4.4.4), the error above is shown after selecting a image.

**Comment by coomar2841** [comment]
Can you post some info from the logcat?

**Comment by coomar2841** [comment]
Can you check again. It should be fine now.
