### ISSUE TITLE
How to custom the folder name?

### ISSUE THREAD

**Issue by waikchiu5** [coomar2841/image-chooser-library#162]
i want to stay all the image in the specific folder after chose the image?

I cannot found any method and set the folder name

**Comment by coomar2841** [comment]
You can set it in preferences.

https://github.com/coomar2841/image-chooser-library/blob/dev/image-chooser-library/src/main/java/com/kbeanie/imagechooser/api/BChooserPreferences.java#L23

Else, you can still use the deprecated constructors which takes in a folder name as a parameter.
