### ISSUE TITLE
Image chooser not working on device without sd card????

### ISSUE THREAD

**Issue by saurabh810** [coomar2841/image-chooser-library#174]
Following exception throw in logs

com.kbeanie.imagechooser.exceptions.ChooserException: Error creating directory: /storage/sdcard0/bichooser

**Comment by coomar2841** [comment]
Yes, this is an issue. Would suggest you to use `https://github.com/coomar2841/android-multipicker-library` for now.

**Comment by KanwarPalS** [comment]
+1
https://github.com/coomar2841/android-multipicker-library not works as well

**Comment by coomar2841** [comment]
You can set the location of the temp storage by using CacheLocation. Please open an issue if it's not working.
