### ISSUE TITLE
Out Of Memory Error: HTC Nexus One

### ISSUE THREAD

**Issue by coomar2841** [coomar2841/image-chooser-library#19]
<a href="https://app.crittercism.com/developers/crash-details/97b25a2116d7b2556aeab9d95cb0ca649a91a24364f3dae88acec66b"> View Crash Report on Crittercism </a> 

 Reported by: Kumar Bibek (coomar.101@gmail.com)

Status: Unresolved

This Crash occured 1 times for 1 users

0 java.lang.OutOfMemoryError: bitmap size exceeds VM budget
1 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
2 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:470)
3 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:284)
4 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.compressAndSaveImage(MediaProcessorThread.java:158)
5 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.getThumbnailSmallPath(MediaProcessorThread.java:112)
6 	at com.kbeanie.imagechooser.threads.MediaProcessorThread.createThumbnails(MediaProcessorThread.java:97)
7 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.process(ImageProcessorThread.java:93)
8 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.processImage(ImageProcessorThread.java:85)
9 	at com.kbeanie.imagechooser.threads.ImageProcessorThread.run(ImageProcessorThread.java:54)

**Comment by slmyldz** [comment]
+1
