### ISSUE TITLE
Choosing Image from Google Drive app fails

### ISSUE THREAD

**Issue by dmitry-kopitkov** [coomar2841/image-chooser-library#20]
Hi,

I'm using your demo app, I'm choosing image -> complete action using google drive app -> choose some image there.
I see message "couldn't process null file".

please add support for this case.

Thanks,
Dmitry

**Comment by preetb123** [comment]
04-14 20:10:50.172: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.262: D/BatteryStatsImpl(4623): ++++++xy WakeLock start : pid=4623, name=, type=0, tid=4914, pid=4623, pName=null
04-14 20:10:50.282: E/SQLiteLog(5042): (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE;] 
04-14 20:10:50.332: I/ImageChooserManager(5166): File: content://com.google.android.apps.docs.files/exposed_content/cNFxLnGO1QOdRmyk3UqW7g%3D%3D%0A%3BZUi5q5DqJufH6RmME7jdrBFgUY3cAC1GbsItBXxLAjwL5HMjG7j8QekmcQ8YJq8q%0A
04-14 20:10:50.342: I/dalvikvm(5166): Could not find method android.provider.DocumentsContract.isDocumentUri, referenced from method com.kbeanie.imagechooser.threads.MediaProcessorThread.getPath
04-14 20:10:50.342: W/dalvikvm(5166): VFY: unable to resolve static method 1032: Landroid/provider/DocumentsContract;.isDocumentUri (Landroid/content/Context;Landroid/net/Uri;)Z
04-14 20:10:50.342: D/dalvikvm(5166): VFY: replacing opcode 0x71 at 0x000c
04-14 20:10:50.342: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.352: D/WindowManager(4623): PhoneWindowManager: focusChangedLw
04-14 20:10:50.352: D/WindowManager(4623): updateReadingMode
04-14 20:10:50.362: I/ImageProcessorThread(5166): Processing Image File: content://com.google.android.apps.docs.files/exposed_content/cNFxLnGO1QOdRmyk3UqW7g%3D%3D%0A%3BZUi5q5DqJufH6RmME7jdrBFgUY3cAC1GbsItBXxLAjwL5HMjG7j8QekmcQ8YJq8q%0A
04-14 20:10:50.362: I/MediaProcessorThread(5166): Image Uri: content://com.google.android.apps.docs.files/exposed_content/cNFxLnGO1QOdRmyk3UqW7g%3D%3D%0A%3BZUi5q5DqJufH6RmME7jdrBFgUY3cAC1GbsItBXxLAjwL5HMjG7j8QekmcQ8YJq8q%0A
04-14 20:10:50.362: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.362: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.372: D/WindowManager(4623): This has baseActivity
04-14 20:10:50.372: D/STATUSBAR-StatusBarManagerService(4623): setSystemUiVisibility(0x0)
04-14 20:10:50.372: D/STATUSBAR-StatusBarManagerService(4623): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
04-14 20:10:50.382: D/BatteryStatsImpl(4623): ++++++xy WakeLock stop : pid=4623, name=, type=0, tid=4837, pid=4623, pName=null
04-14 20:10:50.392: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.462: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.472: W/GAV2(5298): Thread[main,5,main]: dispatch call queued.  Need to call GAServiceManager.getInstance().initialize().
04-14 20:10:50.482: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.512: D/NetworkController_dual(4753): onReceive() - RSSI_CHANGED_ACTION, WIFI_STATE, NETWORK_STATE
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM0:systemSimState=1, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM1:systemSimState=0, simActive=1
04-14 20:10:50.512: W/SignalStrength(4753): getGsmLevel=4
04-14 20:10:50.512: W/SignalStrength(4753): getLevel=4 (SignalStrength: 17 0 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 gsm|lte 0x4)
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM0:systemSimState=1, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM1:systemSimState=0, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): getPhoneSignalIconList : mMaxLevelOfSignalStrengthIndicator = 4 inetCondition = 0
04-14 20:10:50.512: D/NetworkController_dual(4753): getPhoneSignalDescriptionIconId : mMaxLevelOfSignalStrengthIndicator = 4 iconLevel = 4
04-14 20:10:50.512: D/NetworkController_dual(4753): getDataSignalIconId : mMaxLevelOfSignalStrengthIndicator = 4 inetCondition = 0 iconLevel = 4
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM0:systemSimState=1, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM1:systemSimState=0, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): updateTelephonySignalStrength() : SIM for updating siginal is different mSimIndex=1
04-14 20:10:50.562: D/ImageChooserExample(5166): onError : Couldn't process a null file
04-14 20:10:50.602: D/dalvikvm(5298): GC_CONCURRENT freed 3808K, 27% free 13248K/18055K, paused 7ms+12ms, total 113ms
04-14 20:10:50.612: D/AbsListView(5298): [unregisterDoubleTapMotionListener]

**Comment by preetb123** [comment]
I got this issue.

Device: samsung duos gt-i8286
OS version: Android 4.1.2


04-14 20:10:50.172: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.262: D/BatteryStatsImpl(4623): ++++++xy WakeLock start : pid=4623, name=, type=0, tid=4914, pid=4623, pName=null
04-14 20:10:50.282: E/SQLiteLog(5042): (5) statement aborts at 1: [PRAGMA journal_mode=TRUNCATE;] 
04-14 20:10:50.332: I/ImageChooserManager(5166): File: content://com.google.android.apps.docs.files/exposed_content/cNFxLnGO1QOdRmyk3UqW7g%3D%3D%0A%3BZUi5q5DqJufH6RmME7jdrBFgUY3cAC1GbsItBXxLAjwL5HMjG7j8QekmcQ8YJq8q%0A
04-14 20:10:50.342: I/dalvikvm(5166): Could not find method android.provider.DocumentsContract.isDocumentUri, referenced from method com.kbeanie.imagechooser.threads.MediaProcessorThread.getPath
04-14 20:10:50.342: W/dalvikvm(5166): VFY: unable to resolve static method 1032: Landroid/provider/DocumentsContract;.isDocumentUri (Landroid/content/Context;Landroid/net/Uri;)Z
04-14 20:10:50.342: D/dalvikvm(5166): VFY: replacing opcode 0x71 at 0x000c
04-14 20:10:50.342: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.352: D/WindowManager(4623): PhoneWindowManager: focusChangedLw
04-14 20:10:50.352: D/WindowManager(4623): updateReadingMode
04-14 20:10:50.362: I/ImageProcessorThread(5166): Processing Image File: content://com.google.android.apps.docs.files/exposed_content/cNFxLnGO1QOdRmyk3UqW7g%3D%3D%0A%3BZUi5q5DqJufH6RmME7jdrBFgUY3cAC1GbsItBXxLAjwL5HMjG7j8QekmcQ8YJq8q%0A
04-14 20:10:50.362: I/MediaProcessorThread(5166): Image Uri: content://com.google.android.apps.docs.files/exposed_content/cNFxLnGO1QOdRmyk3UqW7g%3D%3D%0A%3BZUi5q5DqJufH6RmME7jdrBFgUY3cAC1GbsItBXxLAjwL5HMjG7j8QekmcQ8YJq8q%0A
04-14 20:10:50.362: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.362: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.372: D/WindowManager(4623): This has baseActivity
04-14 20:10:50.372: D/STATUSBAR-StatusBarManagerService(4623): setSystemUiVisibility(0x0)
04-14 20:10:50.372: D/STATUSBAR-StatusBarManagerService(4623): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
04-14 20:10:50.382: D/BatteryStatsImpl(4623): ++++++xy WakeLock stop : pid=4623, name=, type=0, tid=4837, pid=4623, pName=null
04-14 20:10:50.392: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.462: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.472: W/GAV2(5298): Thread[main,5,main]: dispatch call queued.  Need to call GAServiceManager.getInstance().initialize().
04-14 20:10:50.482: D/KeyguardViewMediator(4623): setHidden false
04-14 20:10:50.512: D/NetworkController_dual(4753): onReceive() - RSSI_CHANGED_ACTION, WIFI_STATE, NETWORK_STATE
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM0:systemSimState=1, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM1:systemSimState=0, simActive=1
04-14 20:10:50.512: W/SignalStrength(4753): getGsmLevel=4
04-14 20:10:50.512: W/SignalStrength(4753): getLevel=4 (SignalStrength: 17 0 -120 -160 -120 -1 -1 99 2147483647 2147483647 2147483647 2147483647 gsm|lte 0x4)
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM0:systemSimState=1, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM1:systemSimState=0, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): getPhoneSignalIconList : mMaxLevelOfSignalStrengthIndicator = 4 inetCondition = 0
04-14 20:10:50.512: D/NetworkController_dual(4753): getPhoneSignalDescriptionIconId : mMaxLevelOfSignalStrengthIndicator = 4 iconLevel = 4
04-14 20:10:50.512: D/NetworkController_dual(4753): getDataSignalIconId : mMaxLevelOfSignalStrengthIndicator = 4 inetCondition = 0 iconLevel = 4
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM0:systemSimState=1, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): getNumberOfSim() SIM1:systemSimState=0, simActive=1
04-14 20:10:50.512: D/NetworkController_dual(4753): updateTelephonySignalStrength() : SIM for updating siginal is different mSimIndex=1
04-14 20:10:50.562: D/ImageChooserExample(5166): onError : Couldn't process a null file
04-14 20:10:50.602: D/dalvikvm(5298): GC_CONCURRENT freed 3808K, 27% free 13248K/18055K, paused 7ms+12ms, total 113ms
04-14 20:10:50.612: D/AbsListView(5298): [unregisterDoubleTapMotionListener]
