### ISSUE TITLE
When picking just Image, google Photos app allows to pick also videos

### ISSUE THREAD

**Issue by dimka-kopitkov** [coomar2841/image-chooser-library#28]
In Demo app, got to Image Chooser
Click "Choose Image"
Complete action using google's "Photos" app
There you can see images and videos
When picking video file, I see message in Demo app:
Corrupt or deleted file??

**Comment by coomar2841** [comment]
Doesn't seem to be an issue anymore. Although, if the Photos app is showing videos also, I don't think we can do much about it.
