### ISSUE TITLE
Others Folders Images Problem

### ISSUE THREAD

**Issue by naveedahmad99** [coomar2841/image-chooser-library#32]
I was working with this library, When I choose images from other folder like CameraSample Photos, so the Toast Appeared that file not found.
![screenshot_2014-05-12-14-58-10](https://cloud.githubusercontent.com/assets/5438968/2942993/d69dfaa6-d9bc-11e3-9d55-04de06277470.png)

**Comment by nidobeb** [comment]
Sorry for the late reply, this library is not working for picassa images.

**Comment by coomar2841** [comment]
Can you post some logs if it's still an issue for you?

**Comment by coomar2841** [comment]
It's fixed now. Closing this issue.
