### ISSUE TITLE
"onActivityResult requestCode is different from the type the chooser was initialized with." error

### ISSUE THREAD

**Issue by cokeby190** [coomar2841/image-chooser-library#37]
Got this error :

"onActivityResult requestCode is different from the type the chooser was initialized with."

on Samsung S3 device, 

for requestCode : 
ChooserType.REQUEST_PICK_PICTURE 
OR 
ChooserType.REQUEST_CAPTURE_PICTURE

when trying to take picture / choose from Gallery. 

Any idea what could have been causing it?

![screen shot 2014-08-12 at 6 24 26 pm](https://cloud.githubusercontent.com/assets/1791974/3889241/5252c230-220b-11e4-9002-8d8eb5839738.png)

**Comment by jagatappv** [comment]
Can you tell me how can i use onSaveInstanceState  with Fragments??

Thanks in advance
