### ISSUE TITLE
Please update build.gradle dependencies

### ISSUE THREAD

**Issue by timmolter** [coomar2841/image-chooser-library#45]
Should be:

    dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        compile 'com.android.support:appcompat-v7:21.+'
        compile project(':image-chooser-library')
        compile 'com.google.android.gms:play-services:6.+'
    }

**Comment by coomar2841** [comment]
Fixed. Took a long time to make these minor changes. Sorry.
