### ISSUE TITLE
Please add multi-choice

### ISSUE THREAD

**Issue by mkosik** [coomar2841/image-chooser-library#46]
Choosing multiple images / videos / files at once is fundamental, because if user is allowd e.g. to upload multiple images, it's the worst UX if it has to add each manually.

Could you please add multi-choice? Can anybody in meantime suggest how to achieve that with this lib?

**Comment by wangyeming** [comment]
Hello， @coomar2841.  Does this library support multi-choice feature now? Thank you!:-D

**Comment by coomar2841** [comment]
Nope. Not yet.


*Thanks and Regards,Kumar Bibek*


*http://techdroid.kbeanie.com
<http://techdroid.kbeanie.com>http://www.kbeanie.com
<http://www.kbeanie.com>*

**Comment by coomar2841** [comment]
Multi-choice is added now. in version 1.5.7. Check it out.
