### ISSUE TITLE
Get extra's from ChooserManager

### ISSUE THREAD

**Issue by dremex** [coomar2841/image-chooser-library#50]
Hello,

Thanks to #34 it's possible to set extra's on ChooserManager's but I can't find a way to retrieve these afterwards, is this currently possible or would it require a new getter to fetch these?

Thanks

**Comment by coomar2841** [comment]
Hmm, will need to add a setter method for that. Will look into that. Just wondering as to why you would need that info?

**Comment by dremex** [comment]
My app allows users to take different "types" of photos via different buttons. Currently I have to track what type of photo is being taken via a global variable in the activity whereas I'd like to simply pass it as an extra to my ChooserManager and then retrieve it after the photo has been taken (inside the onImageChosen callback).

**Comment by naphtul** [comment]
I have a very similar issue to @dremex.
@coomar2841 , it would be great to have it!

**Comment by coomar2841** [comment]
Ok, Will add it with the next release. Thanks for your inputs.

**Comment by coomar2841** [comment]
Done.
