### ISSUE TITLE
Picking image fails using external storage on Lollipop

### ISSUE THREAD

**Issue by Jaymassena** [coomar2841/image-chooser-library#51]
This may not be limited to lollipop. The image is stored on the device in Pictures/Instragram. Using the "Images" provider succeeds and this is the returned uri:
content://com.android.providers.media.documents/document/image%3A13194

Using the "Internal storage" provider to pick the same image fails with error toast "Couldn't process a null file". Here is the returned uri:
content://com.android.externalstorage.documents/document/primary%3APictures%2FInstagram%2FIMG_20141104_183552.jpg

**Comment by coomar2841** [comment]
How do you get to choose the Internal Storage?

**Comment by Jaymassena** [comment]
Here is a screen shot of the document browser after opening it from the image chooser demo app. The option to hide or show the internal storage item is in the overflow menu items:

![device-2015-01-26-074040](https://cloud.githubusercontent.com/assets/455451/5902374/d0bb855c-a52e-11e4-906b-cbba2f10139c.png)

**Comment by coomar2841** [comment]
Thanks... Will look into this soon.

**Comment by darjidhruvit** [comment]
any update for lollipop ? i get null every time when i picked up image from gallery or photos

**Comment by coomar2841** [comment]
Fixed.  Will be released with 1.5.0
