### ISSUE TITLE
Document browser has two entry points for Onedrive and one of them fails

### ISSUE THREAD

**Issue by Jaymassena** [coomar2841/image-chooser-library#52]
Not quite sure the best way to describe this. The kitkat+ document browser navigation drawer has upper and lower sections. For me on lollipop the upper section has document providers like Images, Downloads, Recent, Internal storage, Drive and OneDrive. The lower section has Photos, OneDrive plus others.

When I use OneDrive from the upper section, I get a fail in the image chooser library with error toast "file not found". Here is the uri:
content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2Fproperty%2Fjay%2540ariseditions.com%2FD5796D89F69EDE94!59186%2FSnow%25202012%2520008.JPG

When I use OneDrive from the lower section, the operation succeeds. Here is the uri:
file:///storage/emulated/0/Android/data/com.microsoft.skydrive/cache/SkyDriveCacheFile_2304.cachedata/Snow%202012%20008.JPG

**Comment by coomar2841** [comment]
Yes, I can reproduce this. Thanks for the report.

**Comment by coomar2841** [comment]
This should be fixed now. Please check it out in version 1.5.7
