### ISSUE TITLE
Images bimagechooser

### ISSUE THREAD

**Issue by Tictok91** [coomar2841/image-chooser-library#57]
when saving the photo or image from gallery, the pictures stored on previous days seem to get deleted from the bimagechooser folder...

**Comment by Jaymassena** [comment]
I've also seen photos saved to my app folder in the Pictures directory disappear but haven't been able to nail down the repro steps.

**Comment by coomar2841** [comment]
There's a cache limit built into the library, which I thought would be helpful. But, now, I think I should be removing it. Thanks for the issue.

**Comment by Tictok91** [comment]
ok please notify me when this issue has been solved.
Thanks

**Comment by coomar2841** [comment]
Fixed.
