### ISSUE TITLE
Add to Maven Central?

### ISSUE THREAD

**Issue by hidabe** [coomar2841/image-chooser-library#6]
I like this library, i think that it is good.

You could add it to Maven Central for integrate it?

I am, too, writing library about upload any Multipart/POST content to server. I think that i could use your library, replacing my own library, and, if you upload to Maven Central and add support for Maven, it will be more easy.

It is my library: https://github.com/sopinet/android-mediauploader

I can help you for add Maven support too.

Thanks, regards!

**Comment by coomar2841** [comment]
Thanks for all your help people. Closing this issue finally :)
