### ISSUE TITLE
Picking from gallery works great!! Capture doesn't with "Could't process a null file"

### ISSUE THREAD

**Issue by fwhenin** [coomar2841/image-chooser-library#61]
my code for the two is very similar

```
private void displayImagePicker(int type){
        chooserType = type;
        imageChooserManager = new ImageChooserManager(this, type, "AutosoftFlexMobile", false);
        imageChooserManager.setImageChooserListener(this);
        try {
            imageChooser = imageChooserManager.choose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {

        if (resultCode == getActivity().RESULT_OK &&
                (requestCode == ChooserType.REQUEST_PICK_PICTURE ||
                        requestCode == ChooserType.REQUEST_CAPTURE_PICTURE)) {
            chooserType = requestCode;
            if (imageChooserManager == null){
                reinitializeImageChooser();
            }
            imageChooserManager.submit(requestCode, data);
        }

        super.onActivityResult(requestCode, resultCode, data);
    }
```

So everything is good for picking a picture from gallery, but when I use the camera, I take a picture, hit 'Save' then it goes to a blank screen, the reason is 'Couldn't process a null file' then the app crashes. any help would be great

**Comment by fwhenin** [comment]
Update: I got it not to crash..but still a null image gets passed

**Comment by coomar2841** [comment]
You should save the image path, and re-initialize it with that. This should fix it.

filePath = imageChooserManager.choose();

imageChooserManager.reinitialize(filePath);

**Comment by fwhenin** [comment]
well the filePath during reinitialize is null for both after the user selects or captures an image

**Comment by fwhenin** [comment]
'''
    private void reinitializeImageChooser() {
        imageChooserManager = new ImageChooserManager(this, chooserType, "AutosoftFlexMobile", false);
        imageChooserManager.setImageChooserListener(this);
        imageChooserManager.reinitialize(imageChooser); // imageChooser here is always null
    }
'''

**Comment by coomar2841** [comment]
Could you try the sample app and see if it's still the same problem? If yes, then I can look into this.

**Comment by fwhenin** [comment]
I tried it...and it works there. but my code is inside a fragment not an activity

**Comment by fwhenin** [comment]
this is definitely something I'm doing, I just don't know what it is lol

**Comment by coomar2841** [comment]
Ok, So, first thing, is probably because your activity is being destroyed. When you call this,

<pre>
filePath = imageChooserManager.choose();
</pre>

Can you check if at this point, it is null in the logs?

**Comment by fwhenin** [comment]
it's not null there...it's null at reinitialize

**Comment by fwhenin** [comment]
I'm looking now into using onSaveInstanceState and saving it there.

**Comment by fwhenin** [comment]
GOT IT

'''
@Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);

        outState.putString("imageChooser", imageChooser);
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        if (savedInstanceState != null){
            imageChooser = savedInstanceState.getString("imageChooser", null);
        }

    }
'''

had to save the imageChooser and get it from the instancestate
