### ISSUE TITLE
Issue with integrating Fragements

### ISSUE THREAD

**Issue by jagatappv** [coomar2841/image-chooser-library#66]
Hey,

I have tried this library.

Working fine with activity.

Now i have to use this library in fragment but its not returning result.

Can you help me to integrate this with fragment?

Thanks

**Comment by coomar2841** [comment]
Could you put logs and see on both Activity's and Fragment's onActivityResult parts, to see if it is getting called in any one of them?

**Comment by jagatappv** [comment]
Hey,

thanks for replay

I have putted log inside inActivityResult, but not getting anything in it.

**Comment by coomar2841** [comment]
Have you implemented onSaveInstance and onRestore? May be your activity is getting killed? Put logs in your onDestroy methods to confirm.

**Comment by jagatappv** [comment]
I have added My fragment inside one activity. So i am sure its not killed, otherwise the fragment itself killed.

**Comment by coomar2841** [comment]
Could you post some logs?

**Comment by jagatappv** [comment]
Sorry , But i am not getting any log. I just have call above code (chooseImage()) ,i  have select image from gallery, then i am not getting any result from onActivitiResult .

**Comment by coomar2841** [comment]
Can you try out the sample and look at the source for the fragment example? Closing this for now. Please open a new one if the issue persists.
