### ISSUE TITLE
Image chooser not working with fragments

### ISSUE THREAD

**Issue by jagatappv** [coomar2841/image-chooser-library#68]
Hi,

I have Integrated this library in my code within fragment.

I am getting this error "onActivityResult requestCode is different from the type the chooser was initialized with. "

Can anyone help me to resolve this??

Thanks in Advance

**Comment by coomar2841** [comment]
You should reinitialize it properly. I still haven't put in a sample yet, but give me a day or two and I will do that.

**Comment by jagatappv** [comment]
Thanks for support

**Comment by egslava** [comment]
Any solution?

**Comment by coomar2841** [comment]
I have added a sample in the dev-refactor branch. It's not yet merged with the other branches. But that should work for you. Sorry for taking so long, although it was just a few minutes of work. Hope this helps you in integration with Fragments.

**Comment by jagatappv** [comment]
Can i access that branch?

**Comment by coomar2841** [comment]
Yes, of course.

**Comment by jagatappv** [comment]
Thanks a lot.

**Comment by coomar2841** [comment]
Closing this issue now. Hope the example helps you.
