### ISSUE TITLE
Pick video from camera in < Android 2.3

### ISSUE THREAD

**Issue by hidabe** [coomar2841/image-chooser-library#7]
I have found one error picking video from Camera in Android 2.3 or before. Error is:
08-21 13:03:00.900: E/AndroidRuntime(23720):    at com.sec.android.app.camera.CamcorderEngine.renameTempFile(CamcorderEngine.java:1357)

I have found any information about it, 
http://stackoverflow.com/questions/10494839/verifiyandsetparameter-error-when-trying-to-record-video

It is MediaStore.EXTRA_OUTPUT issue

**Comment by puth** [comment]
My file is png file but after I use this library it content type change to jpeg
