### ISSUE TITLE
Manifest merger fails due to app icon

### ISSUE THREAD

**Issue by Transformat** [coomar2841/image-chooser-library#70]
Error:(52, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@drawable/app_icon) from AndroidManifest.xml:52:9
  	is also present at com.kbeanie:image-chooser-library:1.4.3:13:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:49:5 to override

tools:replace="android:icon" not working

**Comment by coomar2841** [comment]
That's strange. I haven't had any problems before. Will check this.

**Comment by Jaymassena** [comment]
Saw the same thing. Renamed my icon resource as a temp work around.

**Comment by zmingchun** [comment]
As the Android studio say , we should add
```xml
tools:replace="android:icon 
``` 
in out project **AndroidManifest.xml**，before use *tools* tag，you should add 
```xml
          xmlns:tools="http://schemas.android.com/tools"
```
in **manifest** tag.

Above work for me.

**Comment by Transformat** [comment]
I think the original developer should remove that line from the repo itself. It will never cause any issues then.

**Comment by desgraci** [comment]
using compile 'com.kbeanie:image-chooser-library:1.4.3@aar', problem persist
"	is also present at com.kbeanie:image-chooser-library:1.4.3:13:9 value=(@drawable/ic_launcher)
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:9:5 to override"
