### ISSUE TITLE
OnImageChosen didn't called. 

### ISSUE THREAD

**Issue by RokasAug** [coomar2841/image-chooser-library#78]
I have implemented ImageChooserListener to my fragment, call this method on button click:
```
    private void chooseImage() {
        ImageChooserManager imageChooserManager = new ImageChooserManager(this,
                ChooserType.REQUEST_PICK_PICTURE, "myfolder", true);
        imageChooserManager.setImageChooserListener(this);
        try {
            String filePath = imageChooserManager.choose();
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

but after I choose image OnImageChosen didn't call. 

```
    @Override
    public void onImageChosen(ChosenImage chosenImage) {
        Log.d("SYSOUT", "WHAAAAAAT?");
        addPhotoButton.setBackground(Drawable.createFromPath(chosenImage.getFilePathOriginal()));

    }
```

What could be the problem? 

@dalinaum , @coomar2841 , @dimka-kopitkov , @abdyer , @juandiana 

Thanks.

**Comment by abdyer** [comment]
Did you call `imageChooserManager.submit(requestCode, data)` in `onActivityResult` as shown [here](https://github.com/coomar2841/image-chooser-library/blob/dev/app/src/main/java/com/beanie/imagechooserapp/ImageChooserActivity.java#L127)?

**Comment by RokasAug** [comment]
I missed it. It works now. Thank you!
