### ISSUE TITLE
Deleting the original file

### ISSUE THREAD

**Issue by idanbar134** [coomar2841/image-chooser-library#81]
Hello,

After i take picture i send it to remote server and immediately need to delete it from the internal storage and external storage.
from the application lib i deleted the 3 (original, small thum, big thumb) files successfully. The rest of images stays in the same folder where thy where captured.

Waiting for your response.
Best
Idan

**Comment by coomar2841** [comment]
Not sure what are you expecting. Can you please be elaborate?

**Comment by dzfacts** [comment]
how do I delete the files from bimagechooser and bvideochooser ?

**Comment by coomar2841** [comment]
You have file paths to all the images, right? So, you can delete them manually. The library yet, doesn't track all the urls that it generates. May be I can add it as a feature.
