### ISSUE TITLE
Add a new selection that not to save image file. 

### ISSUE THREAD

**Issue by wangyeming** [coomar2841/image-chooser-library#90]
For example, I use this library to choose one image file and turn to crop activity. I want to save the cropped image file but not want to copy the origin image files. 
Thanks for your library, it's very useful for my develop work.

**Comment by coomar2841** [comment]
You can take the image, crop it, and save the cropped image and delete the other files. Right now, I am not sure if I can do it in the library for you.

**Comment by wangyeming** [comment]
Thanks for your advice~

**Comment by coomar2841** [comment]
Closing this.
